# Generated by Django 3.2.8 on 2021-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exh', models.CharField(max_length=50, verbose_name='name_of_exh')),
                ('about_of_exh', models.CharField(max_length=255, verbose_name='about_of_exh')),
                ('start_time', models.CharField(max_length=25, verbose_name='about_of_exh')),
                ('end_time', models.CharField(max_length=25, verbose_name='about_of_exh')),
            ],
        ),
    ]
