# Generated by Django 3.2.8 on 2021-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/', verbose_name='Изображение'),
        ),
    ]
