# Generated by Django 3.2.8 on 2021-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211018_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='about_of_exh',
            field=models.CharField(max_length=255, verbose_name='Об выставке'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_time',
            field=models.CharField(max_length=25, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='name_of_exh',
            field=models.CharField(max_length=50, verbose_name='Название выставки'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_time',
            field=models.CharField(max_length=25, verbose_name='Дата начала'),
        ),
    ]
