# Generated by Django 3.2.8 on 2021-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exhibition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
