# Generated by Django 3.2.8 on 2021-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exhibition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='about_of_exh',
            field=models.CharField(max_length=280, verbose_name='Об выставке'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_time',
            field=models.CharField(max_length=12, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='name_of_exh',
            field=models.CharField(max_length=32, verbose_name='Название выставки'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_time',
            field=models.CharField(max_length=12, verbose_name='Дата начала'),
        ),
    ]
