# Generated by Django 3.2.8 on 2021-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211018_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='about_of_exh',
            field=models.CharField(max_length=300, verbose_name='Об выставке'),
        ),
    ]
