# Generated by Django 3.2.8 on 2021-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_exhibition_about_of_exh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='about_of_exh',
            field=models.CharField(max_length=420, verbose_name='Об выставке'),
        ),
    ]
