# Generated by Django 3.2.8 on 2021-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_exhibition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Vladik\\Desktop\\dj\\webtest\\main\\media', verbose_name='Изображение'),
        ),
    ]
