# Generated by Django 3.2.8 on 2021-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_exhibition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='published',
            field=models.DateField(auto_now=True),
        ),
    ]
