# Generated by Django 3.2.8 on 2021-10-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_exhibition_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='days_of_exh',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='places',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
    ]
