# Generated by Django 3.2.8 on 2021-10-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211023_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='days_of_exh',
            field=models.IntegerField(default=0, verbose_name='Дней для посещений'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='places',
            field=models.IntegerField(default=1, verbose_name='Количество мест в день'),
        ),
    ]
