# Generated by Django 3.2.8 on 2021-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211023_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_time',
            field=models.DateField(),
        ),
    ]
