# Generated by Django 3.2.8 on 2021-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211024_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='end_time_1',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='start_time_1',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='end_time',
            field=models.CharField(default=1, max_length=12, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_time',
            field=models.CharField(default=0, max_length=12, verbose_name='Дата начала'),
        ),
    ]
