# Generated by Django 3.2.8 on 2021-10-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211024_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='days_of_exh',
        ),
    ]
