# Generated by Django 3.2.8 on 2021-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_exhibition_days_of_exh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='places',
            field=models.IntegerField(default=1, verbose_name='Всего мест'),
        ),
    ]
