# Generated by Django 3.2.8 on 2021-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_exhibition_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='start_time',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='period_time',
            field=models.DurationField(null=True),
        ),
    ]
