# Generated by Django 3.2.8 on 2021-10-25 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_auto_20211025_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exhibition', unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_of_ticket',
            field=models.IntegerField(unique=True),
        ),
    ]
